# Generated by Django 5.1.2 on 2024-10-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
            ],
            options={
                'db_table': 'Crud',
            },
        ),
    ]
